name: Build & publish docker images

on:
  release:
    types:
      - prereleased
      - released

jobs:
  docker-build:
    name: docker-build
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v4

      - name: Set tag name from release
        id: set-tag-name
        run: |
          echo "TAG_NAME=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to AWS ECR
        run: |
          aws configure set aws_access_key_id ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.ECR_AWS_REGION }}
          aws ecr get-login-password --region ${{ secrets.ECR_AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.ECR_AWS_REGION }}.amazonaws.com

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.ECR_AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.ECR_AWS_REGION }}.amazonaws.com/${{ github.repository }}:${{ env.TAG_NAME }}
          platforms: linux/amd64,linux/arm64/v8
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: true
